-- CreateEnum
CREATE TYPE "CargoRole" AS ENUM ('PASTOR', 'DIACONO', 'PRESBITERO', 'EVANGELISTA', 'MISSIONARIO', 'SECRETARIO', 'TESOUREIRO', 'PASTOR_PRESIDENTE', 'PASTOR_DIRIGENTE', 'MUSICO', 'AUXILIAR');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "cargo" "CargoRole";
